name: collect new articles

on: 
  # schedule:
    # - cron: "0 */12 * * *"
  workflow_dispatch:
  #   inputs:
  #     start_date:
  #       required: true
  #       type: string
  #     end_date:
  #       required: true
  #       type: string
  #     num_threads:
  #       required: true
  #       default: "4"
  #       type: string
        
jobs:
  collect-articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Repository B
        uses: actions/checkout@v3
        with:
          repository: 'deep-diver/paper-reviewer' # Replace with the actual owner and name of repository B
          token: ${{ secrets.GH_TOKEN }} # Create a PAT with read access to repository B and store it as a secret in repository A
          path: 'paper-reviewer'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup dependencies and run the script
        run: |
          cur_date=$(date '+%Y-%m-%d')
          cd paper-reviewer
          
          pip install -r requirements.txt
          sudo apt install poppler-utils
          
          sudo chmod 777 ./collect-hf-linux.sh
          sudo chmod 777 ./convert-hf-linux.sh

          echo $cur_date
          echo "running collect-hf-linux.sh script....."
          
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
          UPSTAGE_API_KEY=${{ secrets.UPSTAGE_API_KEY }} \
          ./collect-hf-linux.sh \
            $cur_date \
            $cur_date \
            8 \
            ../content/paper-reviews

          echo "running convert-hf-linux.sh script....."

          R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }} \
          R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }} \
          R2_S3_ENDPOINT_URL=${{ secrets.R2_S3_ENDPOINT_URL }} \
          R2_DOMAIN_NAME=${{ secrets.R2_DOMAIN_NAME }} \
          ./convert-hf-linux.sh \
            $cur_date \
            $cur_date \
            true
          
      - name: Move Articles to Repository A
        run: |
          mv paper-reviewer/articles/* ./content/paper-reviews/ 
          rm -rf paper-reviewer

      - name: Commit and Push Changes
        run: |
          git config user.name 'Chansung'
          git config user.email 'deep.diver.csp@gmail.com'
          git add .
          git commit -m "Automated update of static pages"
          git push
